let oyin=prompt("Atak o'qib maza qilas lekin")
let hello=alert("Assalomu alekum")
let gaem=prompt("Ha yoki Yo' o'yniniy oynimza ")
let boshladi1=prompt("O'qiysizmi?")
let boshladi2=prompt("Iwlismi")
let boshladi3=prompt("Yozgan narsam ko'rinvotimi")
let boshladi4=prompt("Site yaxwi chiqanmi")
let boshladi5=prompt("oka ismiz TAPORMI")
let boshladi6=prompt("xozi kuldiza brat")
let boshladi7=prompt("kulgan bosez xursandman charchamen")
console.log(oyin, hello, gaem, boshladi1, boshladi2, boshladi3, boshladi4 ,boshladi5, boshladi6, boshladi7)